### ISSUE TITLE
NoSuchMethodError occurred when updating kotlin version to 1.3.70

### ISSUE THREAD

**Issue by nikeorever** [JakeWharton/retrofit2-kotlinx-serialization-converter#15]
org.jetbrains.kotlin:kotlin-serialization:1.3.70
org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.70

`Caused by: java.lang.NoSuchMethodError: kotlinx.serialization.internal.SerialClassDescImpl.<init>(Ljava/lang/String;Lkotlinx/serialization/internal/GeneratedSerializer;I)V
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.KotlinSerializationConverterFactoryBytesTest$User$$serializer.<clinit>(KotlinSerializationConverterFactoryBytesTest.kt:34)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.KotlinSerializationConverterFactoryBytesTest$User$Companion.serializer(KotlinSerializationConverterFactoryBytesTest.kt)`

**Comment by nikeorever** [comment]
Duplicate of #14
